version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  client:
    build:
      dockerfile: Dockerfile.client
      context: ./
    volumes:
      - ./:/app
    ports:
      - '8000:8000'
    depends_on:
      - db

